ALTER TABLE BUSINESS_DESCR DROP DESCR;
ALTER TABLE BUSINESS_DESCR ADD DESCR TEXT AFTER LANG_CODE;

ALTER TABLE CONTACT_DESCR DROP DESCR;
ALTER TABLE CONTACT_DESCR ADD DESCR TEXT AFTER LANG_CODE;

ALTER TABLE SERVICE_DESCR DROP DESCR;
ALTER TABLE SERVICE_DESCR ADD DESCR TEXT AFTER LANG_CODE;

ALTER TABLE BINDING_DESCR DROP DESCR;
ALTER TABLE BINDING_DESCR ADD DESCR TEXT AFTER LANG_CODE;

ALTER TABLE TMODEL_INSTANCE_INFO_DESCR DROP DESCR;
ALTER TABLE TMODEL_INSTANCE_INFO_DESCR ADD DESCR TEXT AFTER LANG_CODE;

ALTER TABLE INSTANCE_DETAILS_DESCR DROP DESCR;
ALTER TABLE INSTANCE_DETAILS_DESCR ADD DESCR TEXT AFTER LANG_CODE;

ALTER TABLE INSTANCE_DETAILS_DOC_DESCR DROP DESCR;
ALTER TABLE INSTANCE_DETAILS_DOC_DESCR ADD DESCR TEXT AFTER LANG_CODE;

ALTER TABLE TMODEL_DESCR DROP DESCR;
ALTER TABLE TMODEL_DESCR ADD DESCR TEXT AFTER LANG_CODE;

ALTER TABLE TMODEL_DOC_DESCR DROP DESCR;
ALTER TABLE TMODEL_DOC_DESCR ADD DESCR TEXT AFTER LANG_CODE;

ALTER TABLE BUSINESS_CATEGORY DROP KEY_VALUE;
ALTER TABLE BUSINESS_CATEGORY ADD KEY_VALUE TEXT AFTER KEY_NAME;

ALTER TABLE SERVICE_CATEGORY DROP KEY_VALUE;
ALTER TABLE SERVICE_CATEGORY ADD KEY_VALUE TEXT AFTER KEY_NAME;